services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_DOMAIN=easyform.dev
    volumes:
      - /var/dalion/motorsports/docker-compose/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/dalion/motorsports/docker-compose/nginx/config/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - /var/dalion/motorsports/docker-compose/nginx/config/api_conf.d:/etc/nginx/api_conf.d:ro
      - /var/dalion/motorsports/certs/:/etc/certs/public/:ro
    networks:
      - motorsports_network
    logging:
      options:
        max-size: "25m"
        max-file: "3"  

networks:
  motorsports_network:
    name: motorsports_net
    external: true