services:
  nginx:
    image: motorsports:latest
    container_name: motorsports
    restart: unless-stopped
    environment:
      - ConnectionStrings__Motorsports=server=localhost;database=motorsports;user=motorsports;password=S3cr37_1234
      - Kestrel:Endpoints:Http:Url=http://0.0.0.0:80
    networks:
      - motorsports_network

networks:
  motorsports_network:
    name: motorsports_net
    external: true