MERGE [dbo].[Country] AS Target 
USING (SELECT * FROM (VALUES
(N'AD', N'ANDORRA', N'Andorra', N'AND', 20, 376),
(N'AE', N'UNITED ARAB EMIRATES', N'United Arab Emirates', N'ARE', 784, 971),
(N'AF', N'AFGHANISTAN', N'Afghanistan', N'AFG', 4, 93),
(N'AG', N'ANTIGUA AND BARBUDA', N'Antigua and Barbuda', N'ATG', 28, 1268),
(N'AI', N'ANGUILLA', N'Anguilla', N'AIA', 660, 1264),
(N'AL', N'ALBANIA', N'Albania', N'ALB', 8, 355),
(N'AM', N'ARMENIA', N'Armenia', N'ARM', 51, 374),
(N'AN', N'NETHERLANDS ANTILLES', N'Netherlands Antilles', N'ANT', 530, 599),
(N'AO', N'ANGOLA', N'Angola', N'AGO', 24, 244),
(N'AP', N'ASIA PACIFIC REGION', N'Asia / Pacific Region', N'0  ', 0, 0),
(N'AQ', N'ANTARCTICA', N'Antarctica', NULL, NULL, 0),
(N'AR', N'ARGENTINA', N'Argentina', N'ARG', 32, 54),
(N'AS', N'AMERICAN SAMOA', N'American Samoa', N'ASM', 16, 1684),
(N'AT', N'AUSTRIA', N'Austria', N'AUT', 40, 43),
(N'AU', N'AUSTRALIA', N'Australia', N'AUS', 36, 61),
(N'AW', N'ARUBA', N'Aruba', N'ABW', 533, 297),
(N'AX', N'ALAND ISLANDS', N'Aland Islands', N'ALA', 248, 358),
(N'AZ', N'AZERBAIJAN', N'Azerbaijan', N'AZE', 31, 994),
(N'BA', N'BOSNIA AND HERZEGOVINA', N'Bosnia and Herzegovina', N'BIH', 70, 387),
(N'BB', N'BARBADOS', N'Barbados', N'BRB', 52, 1246),
(N'BD', N'BANGLADESH', N'Bangladesh', N'BGD', 50, 880),
(N'BE', N'BELGIUM', N'Belgium', N'BEL', 56, 32),
(N'BF', N'BURKINA FASO', N'Burkina Faso', N'BFA', 854, 226),
(N'BG', N'BULGARIA', N'Bulgaria', N'BGR', 100, 359),
(N'BH', N'BAHRAIN', N'Bahrain', N'BHR', 48, 973),
(N'BI', N'BURUNDI', N'Burundi', N'BDI', 108, 257),
(N'BJ', N'BENIN', N'Benin', N'BEN', 204, 229),
(N'BL', N'SAINT BARTHELEMY', N'Saint Barthelemy', N'BLM', 652, 590),
(N'BM', N'BERMUDA', N'Bermuda', N'BMU', 60, 1441),
(N'BN', N'BRUNEI DARUSSALAM', N'Brunei Darussalam', N'BRN', 96, 673),
(N'BO', N'BOLIVIA', N'Bolivia', N'BOL', 68, 591),
(N'BQ', N'BONAIRE, SINT EUSTATIUS AND SABA', N'Bonaire, Sint Eustatius and Saba', N'BES', 535, 599),
(N'BR', N'BRAZIL', N'Brazil', N'BRA', 76, 55),
(N'BS', N'BAHAMAS', N'Bahamas', N'BHS', 44, 1242),
(N'BT', N'BHUTAN', N'Bhutan', N'BTN', 64, 975),
(N'BV', N'BOUVET ISLAND', N'Bouvet Island', NULL, NULL, 0),
(N'BW', N'BOTSWANA', N'Botswana', N'BWA', 72, 267),
(N'BY', N'BELARUS', N'Belarus', N'BLR', 112, 375),
(N'BZ', N'BELIZE', N'Belize', N'BLZ', 84, 501),
(N'CA', N'CANADA', N'Canada', N'CAN', 124, 1),
(N'CC', N'COCOS (KEELING) ISLANDS', N'Cocos (Keeling) Islands', NULL, NULL, 672),
(N'CD', N'CONGO, THE DEMOCRATIC REPUBLIC OF THE', N'Congo, the Democratic Republic of the', N'COD', 180, 242),
(N'CF', N'CENTRAL AFRICAN REPUBLIC', N'Central African Republic', N'CAF', 140, 236),
(N'CG', N'CONGO', N'Congo', N'COG', 178, 242),
(N'CH', N'SWITZERLAND', N'Switzerland', N'CHE', 756, 41),
(N'CI', N'COTE D''IVOIRE', N'Cote D''Ivoire', N'CIV', 384, 225),
(N'CK', N'COOK ISLANDS', N'Cook Islands', N'COK', 184, 682),
(N'CL', N'CHILE', N'Chile', N'CHL', 152, 56),
(N'CM', N'CAMEROON', N'Cameroon', N'CMR', 120, 237),
(N'CN', N'CHINA', N'China', N'CHN', 156, 86),
(N'CO', N'COLOMBIA', N'Colombia', N'COL', 170, 57),
(N'CR', N'COSTA RICA', N'Costa Rica', N'CRI', 188, 506),
(N'CS', N'SERBIA AND MONTENEGRO', N'Serbia and Montenegro', NULL, NULL, 381),
(N'CU', N'CUBA', N'Cuba', N'CUB', 192, 53),
(N'CV', N'CAPE VERDE', N'Cape Verde', N'CPV', 132, 238),
(N'CW', N'CURACAO', N'Curacao', N'CUW', 531, 599),
(N'CX', N'CHRISTMAS ISLAND', N'Christmas Island', NULL, NULL, 61),
(N'CY', N'CYPRUS', N'Cyprus', N'CYP', 196, 357),
(N'CZ', N'CZECH REPUBLIC', N'Czech Republic', N'CZE', 203, 420),
(N'DE', N'GERMANY', N'Germany', N'DEU', 276, 49),
(N'DJ', N'DJIBOUTI', N'Djibouti', N'DJI', 262, 253),
(N'DK', N'DENMARK', N'Denmark', N'DNK', 208, 45),
(N'DM', N'DOMINICA', N'Dominica', N'DMA', 212, 1767),
(N'DO', N'DOMINICAN REPUBLIC', N'Dominican Republic', N'DOM', 214, 1809),
(N'DZ', N'ALGERIA', N'Algeria', N'DZA', 12, 213),
(N'EC', N'ECUADOR', N'Ecuador', N'ECU', 218, 593),
(N'EE', N'ESTONIA', N'Estonia', N'EST', 233, 372),
(N'EG', N'EGYPT', N'Egypt', N'EGY', 818, 20),
(N'EH', N'WESTERN SAHARA', N'Western Sahara', N'ESH', 732, 212),
(N'ER', N'ERITREA', N'Eritrea', N'ERI', 232, 291),
(N'ES', N'SPAIN', N'Spain', N'ESP', 724, 34),
(N'ET', N'ETHIOPIA', N'Ethiopia', N'ETH', 231, 251),
(N'FI', N'FINLAND', N'Finland', N'FIN', 246, 358),
(N'FJ', N'FIJI', N'Fiji', N'FJI', 242, 679),
(N'FK', N'FALKLAND ISLANDS (MALVINAS)', N'Falkland Islands (Malvinas)', N'FLK', 238, 500),
(N'FM', N'MICRONESIA, FEDERATED STATES OF', N'Micronesia, Federated States of', N'FSM', 583, 691),
(N'FO', N'FAROE ISLANDS', N'Faroe Islands', N'FRO', 234, 298),
(N'FR', N'FRANCE', N'France', N'FRA', 250, 33),
(N'GA', N'GABON', N'Gabon', N'GAB', 266, 241),
(N'GB', N'UNITED KINGDOM', N'United Kingdom', N'GBR', 826, 44),
(N'GD', N'GRENADA', N'Grenada', N'GRD', 308, 1473),
(N'GE', N'GEORGIA', N'Georgia', N'GEO', 268, 995),
(N'GF', N'FRENCH GUIANA', N'French Guiana', N'GUF', 254, 594),
(N'GG', N'GUERNSEY', N'Guernsey', N'GGY', 831, 44),
(N'GH', N'GHANA', N'Ghana', N'GHA', 288, 233),
(N'GI', N'GIBRALTAR', N'Gibraltar', N'GIB', 292, 350),
(N'GL', N'GREENLAND', N'Greenland', N'GRL', 304, 299),
(N'GM', N'GAMBIA', N'Gambia', N'GMB', 270, 220),
(N'GN', N'GUINEA', N'Guinea', N'GIN', 324, 224),
(N'GP', N'GUADELOUPE', N'Guadeloupe', N'GLP', 312, 590),
(N'GQ', N'EQUATORIAL GUINEA', N'Equatorial Guinea', N'GNQ', 226, 240),
(N'GR', N'GREECE', N'Greece', N'GRC', 300, 30),
(N'GS', N'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', N'South Georgia and the South Sandwich Islands', NULL, NULL, 0),
(N'GT', N'GUATEMALA', N'Guatemala', N'GTM', 320, 502),
(N'GU', N'GUAM', N'Guam', N'GUM', 316, 1671),
(N'GW', N'GUINEA-BISSAU', N'Guinea-Bissau', N'GNB', 624, 245),
(N'GY', N'GUYANA', N'Guyana', N'GUY', 328, 592),
(N'HK', N'HONG KONG', N'Hong Kong', N'HKG', 344, 852),
(N'HM', N'HEARD ISLAND AND MCDONALD ISLANDS', N'Heard Island and Mcdonald Islands', NULL, NULL, 0),
(N'HN', N'HONDURAS', N'Honduras', N'HND', 340, 504),
(N'HR', N'CROATIA', N'Croatia', N'HRV', 191, 385),
(N'HT', N'HAITI', N'Haiti', N'HTI', 332, 509),
(N'HU', N'HUNGARY', N'Hungary', N'HUN', 348, 36),
(N'ID', N'INDONESIA', N'Indonesia', N'IDN', 360, 62),
(N'IE', N'IRELAND', N'Ireland', N'IRL', 372, 353),
(N'IL', N'ISRAEL', N'Israel', N'ISR', 376, 972),
(N'IM', N'ISLE OF MAN', N'Isle of Man', N'IMN', 833, 44),
(N'IN', N'INDIA', N'India', N'IND', 356, 91),
(N'IO', N'BRITISH INDIAN OCEAN TERRITORY', N'British Indian Ocean Territory', NULL, NULL, 246),
(N'IQ', N'IRAQ', N'Iraq', N'IRQ', 368, 964),
(N'IR', N'IRAN, ISLAMIC REPUBLIC OF', N'Iran, Islamic Republic of', N'IRN', 364, 98),
(N'IS', N'ICELAND', N'Iceland', N'ISL', 352, 354),
(N'IT', N'ITALY', N'Italy', N'ITA', 380, 39),
(N'JE', N'JERSEY', N'Jersey', N'JEY', 832, 44),
(N'JM', N'JAMAICA', N'Jamaica', N'JAM', 388, 1876),
(N'JO', N'JORDAN', N'Jordan', N'JOR', 400, 962),
(N'JP', N'JAPAN', N'Japan', N'JPN', 392, 81),
(N'KE', N'KENYA', N'Kenya', N'KEN', 404, 254),
(N'KG', N'KYRGYZSTAN', N'Kyrgyzstan', N'KGZ', 417, 996),
(N'KH', N'CAMBODIA', N'Cambodia', N'KHM', 116, 855),
(N'KI', N'KIRIBATI', N'Kiribati', N'KIR', 296, 686),
(N'KM', N'COMOROS', N'Comoros', N'COM', 174, 269),
(N'KN', N'SAINT KITTS AND NEVIS', N'Saint Kitts and Nevis', N'KNA', 659, 1869),
(N'KP', N'KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF', N'Korea, Democratic People''s Republic of', N'PRK', 408, 850),
(N'KR', N'KOREA, REPUBLIC OF', N'Korea, Republic of', N'KOR', 410, 82),
(N'KW', N'KUWAIT', N'Kuwait', N'KWT', 414, 965),
(N'KY', N'CAYMAN ISLANDS', N'Cayman Islands', N'CYM', 136, 1345),
(N'KZ', N'KAZAKHSTAN', N'Kazakhstan', N'KAZ', 398, 7),
(N'LA', N'LAO PEOPLE''S DEMOCRATIC REPUBLIC', N'Lao People''s Democratic Republic', N'LAO', 418, 856),
(N'LB', N'LEBANON', N'Lebanon', N'LBN', 422, 961),
(N'LC', N'SAINT LUCIA', N'Saint Lucia', N'LCA', 662, 1758),
(N'LI', N'LIECHTENSTEIN', N'Liechtenstein', N'LIE', 438, 423),
(N'LK', N'SRI LANKA', N'Sri Lanka', N'LKA', 144, 94),
(N'LR', N'LIBERIA', N'Liberia', N'LBR', 430, 231),
(N'LS', N'LESOTHO', N'Lesotho', N'LSO', 426, 266),
(N'LT', N'LITHUANIA', N'Lithuania', N'LTU', 440, 370),
(N'LU', N'LUXEMBOURG', N'Luxembourg', N'LUX', 442, 352),
(N'LV', N'LATVIA', N'Latvia', N'LVA', 428, 371),
(N'LY', N'LIBYAN ARAB JAMAHIRIYA', N'Libyan Arab Jamahiriya', N'LBY', 434, 218),
(N'MA', N'MOROCCO', N'Morocco', N'MAR', 504, 212),
(N'MC', N'MONACO', N'Monaco', N'MCO', 492, 377),
(N'MD', N'MOLDOVA, REPUBLIC OF', N'Moldova, Republic of', N'MDA', 498, 373),
(N'ME', N'MONTENEGRO', N'Montenegro', N'MNE', 499, 382),
(N'MF', N'SAINT MARTIN', N'Saint Martin', N'MAF', 663, 590),
(N'MG', N'MADAGASCAR', N'Madagascar', N'MDG', 450, 261),
(N'MH', N'MARSHALL ISLANDS', N'Marshall Islands', N'MHL', 584, 692),
(N'MK', N'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', N'Macedonia, the Former Yugoslav Republic of', N'MKD', 807, 389),
(N'ML', N'MALI', N'Mali', N'MLI', 466, 223),
(N'MM', N'MYANMAR', N'Myanmar', N'MMR', 104, 95),
(N'MN', N'MONGOLIA', N'Mongolia', N'MNG', 496, 976),
(N'MO', N'MACAO', N'Macao', N'MAC', 446, 853),
(N'MP', N'NORTHERN MARIANA ISLANDS', N'Northern Mariana Islands', N'MNP', 580, 1670),
(N'MQ', N'MARTINIQUE', N'Martinique', N'MTQ', 474, 596),
(N'MR', N'MAURITANIA', N'Mauritania', N'MRT', 478, 222),
(N'MS', N'MONTSERRAT', N'Montserrat', N'MSR', 500, 1664),
(N'MT', N'MALTA', N'Malta', N'MLT', 470, 356),
(N'MU', N'MAURITIUS', N'Mauritius', N'MUS', 480, 230),
(N'MV', N'MALDIVES', N'Maldives', N'MDV', 462, 960),
(N'MW', N'MALAWI', N'Malawi', N'MWI', 454, 265),
(N'MX', N'MEXICO', N'Mexico', N'MEX', 484, 52),
(N'MY', N'MALAYSIA', N'Malaysia', N'MYS', 458, 60),
(N'MZ', N'MOZAMBIQUE', N'Mozambique', N'MOZ', 508, 258),
(N'NA', N'NAMIBIA', N'Namibia', N'NAM', 516, 264),
(N'NC', N'NEW CALEDONIA', N'New Caledonia', N'NCL', 540, 687),
(N'NE', N'NIGER', N'Niger', N'NER', 562, 227),
(N'NF', N'NORFOLK ISLAND', N'Norfolk Island', N'NFK', 574, 672),
(N'NG', N'NIGERIA', N'Nigeria', N'NGA', 566, 234),
(N'NI', N'NICARAGUA', N'Nicaragua', N'NIC', 558, 505),
(N'NL', N'NETHERLANDS', N'Netherlands', N'NLD', 528, 31),
(N'NO', N'NORWAY', N'Norway', N'NOR', 578, 47),
(N'NP', N'NEPAL', N'Nepal', N'NPL', 524, 977),
(N'NR', N'NAURU', N'Nauru', N'NRU', 520, 674),
(N'NU', N'NIUE', N'Niue', N'NIU', 570, 683),
(N'NZ', N'NEW ZEALAND', N'New Zealand', N'NZL', 554, 64),
(N'OM', N'OMAN', N'Oman', N'OMN', 512, 968),
(N'PA', N'PANAMA', N'Panama', N'PAN', 591, 507),
(N'PE', N'PERU', N'Peru', N'PER', 604, 51),
(N'PF', N'FRENCH POLYNESIA', N'French Polynesia', N'PYF', 258, 689),
(N'PG', N'PAPUA NEW GUINEA', N'Papua New Guinea', N'PNG', 598, 675),
(N'PH', N'PHILIPPINES', N'Philippines', N'PHL', 608, 63),
(N'PK', N'PAKISTAN', N'Pakistan', N'PAK', 586, 92),
(N'PL', N'POLAND', N'Poland', N'POL', 616, 48),
(N'PM', N'SAINT PIERRE AND MIQUELON', N'Saint Pierre and Miquelon', N'SPM', 666, 508),
(N'PN', N'PITCAIRN', N'Pitcairn', N'PCN', 612, 0),
(N'PR', N'PUERTO RICO', N'Puerto Rico', N'PRI', 630, 1787),
(N'PS', N'PALESTINIAN TERRITORY, OCCUPIED', N'Palestinian Territory, Occupied', NULL, NULL, 970),
(N'PT', N'PORTUGAL', N'Portugal', N'PRT', 620, 351),
(N'PW', N'PALAU', N'Palau', N'PLW', 585, 680),
(N'PY', N'PARAGUAY', N'Paraguay', N'PRY', 600, 595),
(N'QA', N'QATAR', N'Qatar', N'QAT', 634, 974),
(N'RE', N'REUNION', N'Reunion', N'REU', 638, 262),
(N'RO', N'ROMANIA', N'Romania', N'ROM', 642, 40),
(N'RS', N'SERBIA', N'Serbia', N'SRB', 688, 381),
(N'RU', N'RUSSIAN FEDERATION', N'Russian Federation', N'RUS', 643, 70),
(N'RW', N'RWANDA', N'Rwanda', N'RWA', 646, 250),
(N'SA', N'SAUDI ARABIA', N'Saudi Arabia', N'SAU', 682, 966),
(N'SB', N'SOLOMON ISLANDS', N'Solomon Islands', N'SLB', 90, 677),
(N'SC', N'SEYCHELLES', N'Seychelles', N'SYC', 690, 248),
(N'SD', N'SUDAN', N'Sudan', N'SDN', 736, 249),
(N'SE', N'SWEDEN', N'Sweden', N'SWE', 752, 46),
(N'SG', N'SINGAPORE', N'Singapore', N'SGP', 702, 65),
(N'SH', N'SAINT HELENA', N'Saint Helena', N'SHN', 654, 290),
(N'SI', N'SLOVENIA', N'Slovenia', N'SVN', 705, 386),
(N'SJ', N'SVALBARD AND JAN MAYEN', N'Svalbard and Jan Mayen', N'SJM', 744, 47),
(N'SK', N'SLOVAKIA', N'Slovakia', N'SVK', 703, 421),
(N'SL', N'SIERRA LEONE', N'Sierra Leone', N'SLE', 694, 232),
(N'SM', N'SAN MARINO', N'San Marino', N'SMR', 674, 378),
(N'SN', N'SENEGAL', N'Senegal', N'SEN', 686, 221),
(N'SO', N'SOMALIA', N'Somalia', N'SOM', 706, 252),
(N'SR', N'SURINAME', N'Suriname', N'SUR', 740, 597),
(N'SS', N'SOUTH SUDAN', N'South Sudan', N'SSD', 728, 211),
(N'ST', N'SAO TOME AND PRINCIPE', N'Sao Tome and Principe', N'STP', 678, 239),
(N'SV', N'EL SALVADOR', N'El Salvador', N'SLV', 222, 503),
(N'SX', N'SINT MAARTEN', N'Sint Maarten', N'SXM', 534, 1),
(N'SY', N'SYRIAN ARAB REPUBLIC', N'Syrian Arab Republic', N'SYR', 760, 963),
(N'SZ', N'SWAZILAND', N'Swaziland', N'SWZ', 748, 268),
(N'TC', N'TURKS AND CAICOS ISLANDS', N'Turks and Caicos Islands', N'TCA', 796, 1649),
(N'TD', N'CHAD', N'Chad', N'TCD', 148, 235),
(N'TF', N'FRENCH SOUTHERN TERRITORIES', N'French Southern Territories', NULL, NULL, 0),
(N'TG', N'TOGO', N'Togo', N'TGO', 768, 228),
(N'TH', N'THAILAND', N'Thailand', N'THA', 764, 66),
(N'TJ', N'TAJIKISTAN', N'Tajikistan', N'TJK', 762, 992),
(N'TK', N'TOKELAU', N'Tokelau', N'TKL', 772, 690),
(N'TL', N'TIMOR-LESTE', N'Timor-Leste', NULL, NULL, 670),
(N'TM', N'TURKMENISTAN', N'Turkmenistan', N'TKM', 795, 7370),
(N'TN', N'TUNISIA', N'Tunisia', N'TUN', 788, 216),
(N'TO', N'TONGA', N'Tonga', N'TON', 776, 676),
(N'TR', N'TURKEY', N'Turkey', N'TUR', 792, 90),
(N'TT', N'TRINIDAD AND TOBAGO', N'Trinidad and Tobago', N'TTO', 780, 1868),
(N'TV', N'TUVALU', N'Tuvalu', N'TUV', 798, 688),
(N'TW', N'TAIWAN, PROVINCE OF CHINA', N'Taiwan, Province of China', N'TWN', 158, 886),
(N'TZ', N'TANZANIA, UNITED REPUBLIC OF', N'Tanzania, United Republic of', N'TZA', 834, 255),
(N'UA', N'UKRAINE', N'Ukraine', N'UKR', 804, 380),
(N'UG', N'UGANDA', N'Uganda', N'UGA', 800, 256),
(N'UM', N'UNITED STATES MINOR OUTLYING ISLANDS', N'United States Minor Outlying Islands', NULL, NULL, 1),
(N'US', N'UNITED STATES', N'United States', N'USA', 840, 1),
(N'UY', N'URUGUAY', N'Uruguay', N'URY', 858, 598),
(N'UZ', N'UZBEKISTAN', N'Uzbekistan', N'UZB', 860, 998),
(N'VA', N'HOLY SEE (VATICAN CITY STATE)', N'Holy See (Vatican City State)', N'VAT', 336, 39),
(N'VC', N'SAINT VINCENT AND THE GRENADINES', N'Saint Vincent and the Grenadines', N'VCT', 670, 1784),
(N'VE', N'VENEZUELA', N'Venezuela', N'VEN', 862, 58),
(N'VG', N'VIRGIN ISLANDS, BRITISH', N'Virgin Islands, British', N'VGB', 92, 1284),
(N'VI', N'VIRGIN ISLANDS, U.S.', N'Virgin Islands, U.s.', N'VIR', 850, 1340),
(N'VN', N'VIET NAM', N'Viet Nam', N'VNM', 704, 84),
(N'VU', N'VANUATU', N'Vanuatu', N'VUT', 548, 678),
(N'WF', N'WALLIS AND FUTUNA', N'Wallis and Futuna', N'WLF', 876, 681),
(N'WS', N'SAMOA', N'Samoa', N'WSM', 882, 684),
(N'XK', N'KOSOVO', N'Kosovo', N'---', 0, 381),
(N'YE', N'YEMEN', N'Yemen', N'YEM', 887, 967),
(N'YT', N'MAYOTTE', N'Mayotte', NULL, NULL, 269),
(N'ZA', N'SOUTH AFRICA', N'South Africa', N'ZAF', 710, 27),
(N'ZM', N'ZAMBIA', N'Zambia', N'ZMB', 894, 260),
(N'ZW', N'ZIMBABWE', N'Zimbabwe', N'ZWE', 716, 263)
    )
    AS s (
		[ISO],
		[Name],
		[NiceName],
		[ISO3],
		[NumCode],
		[PhoneCode]
	)) AS Source
ON Target.[ISO] = Source.[ISO]
WHEN NOT MATCHED THEN
INSERT (
    [ISO],
    [Name],
    [NiceName],
    [ISO3],
    [NumCode],
    [PhoneCode]
)
VALUES (
    Source.[ISO],
    Source.[Name],
    Source.[NiceName],
    Source.[ISO3],
    Source.[NumCode],
    Source.[PhoneCode]
);
GO

MERGE [dbo].[Sport] AS Target 
USING (SELECT * FROM (VALUES
        (N'DTM', N'Deutsche Tourenwagen Masters'),
        (N'F1', N'Formula 1'),
        (N'FE', N'Formula E'),
        (N'Indycar', N'Indycar'),
        (N'MotoGP', N'MotoGP'),
        (N'NASCAR', N'NASCAR'),
        (N'WEC', N'World Endurance Championship')
    )
    AS s (
      [Name],
      [FullName]
	)) AS Source
ON Target.[Name] = Source.[Name]
WHEN NOT MATCHED THEN
INSERT (
    [Name],
    [FullName]
)
VALUES (
    Source.[Name],
    Source.[FullName]
);
GO

MERGE [dbo].[Status] AS Target 
USING (SELECT * FROM (VALUES
        (N'Cancelled'),
        (N'Finished'),
        (N'Interrupted'),
        (N'Scheduled')
    )
    AS s (
      [Name]
	)) AS Source
ON Target.[Name] = Source.[Name]
WHEN NOT MATCHED THEN
INSERT (
    [Name]
)
VALUES (
    Source.[Name]
);
GO

IF NOT EXISTS(SELECT * FROM [dbo].[User] WHERE Id = '8500d15b-7ab3-45a0-9547-00e0f6b4a984') BEGIN
  INSERT [dbo].[User] ([Id], [Username], [PasswordHash], [Salt], [Iterations], [Prf], [ForceChangePassword], [Title], [GivenName], [FamilyName], [EmailAddress], [IsDeleted]) VALUES (N'8500d15b-7ab3-45a0-9547-00e0f6b4a984', N'admin', 0x45D367F14F8C118D53C3B1227714EB66DD4610D558DA43C890B93592D330155A, 0x06B218CD4BB89E89839CB28E1B9F42EB, 10000, N'HMACSHA512', 0, N'Mr', NULL, N'Admin', NULL, 0)
END
GO