//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motorsports.Scaffolding.Web.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.RelatedParticipants = new HashSet<Participant>();
            this.RelatedTeams = new HashSet<Team>();
            this.RelatedVenues = new HashSet<Venue>();
        }
    
        public string ISO { get; set; }
        public string Name { get; set; }
        public string NiceName { get; set; }
        public string ISO3 { get; set; }
        public Nullable<short> NumCode { get; set; }
        public Nullable<short> PhoneCode { get; set; }
    
        public virtual ICollection<Participant> RelatedParticipants { get; set; }
        public virtual ICollection<Team> RelatedTeams { get; set; }
        public virtual ICollection<Venue> RelatedVenues { get; set; }
    }
}
