//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motorsports.Scaffolding.Web.App_Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MotorsportsEntities : DbContext
    {
        public MotorsportsEntities()
            : base("name=MotorsportsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<RoundResult> RoundResults { get; set; }
        public virtual DbSet<RoundWinner> RoundWinners { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<SeasonWinner> SeasonWinners { get; set; }
        public virtual DbSet<Sport> Sports { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Venue> Venues { get; set; }
    }
}
