//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motorsports.Scaffolding.Web.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundResult
    {
        public int Round { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Rating { get; set; }
        public Nullable<decimal> Rain { get; set; }
        public Nullable<int> WinningTeam { get; set; }
    
        public virtual Round RelatedRound { get; set; }
        public virtual Status RelatedStatus { get; set; }
        public virtual Team RelatedTeam { get; set; }
    }
}
