//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motorsports.Scaffolding.Web.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public Sport()
        {
            this.RelatedSeasons = new HashSet<Season>();
            this.RelatedTeams = new HashSet<Team>();
        }
    
        public string Name { get; set; }
        public string FullName { get; set; }
    
        public virtual ICollection<Season> RelatedSeasons { get; set; }
        public virtual ICollection<Team> RelatedTeams { get; set; }
    }
}
