//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motorsports.Scaffolding.Web.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.RoundResults = new HashSet<RoundResult>();
            this.RelatedSeasons = new HashSet<Season>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Sport { get; set; }
        public string Country { get; set; }
    
        public virtual Country RelatedCountry { get; set; }
        public virtual ICollection<RoundResult> RoundResults { get; set; }
        public virtual Sport RelatedSport { get; set; }
        public virtual ICollection<Season> RelatedSeasons { get; set; }
    }
}
