//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Motorsports.Scaffolding.Web.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venue
    {
        public Venue()
        {
            this.RelatedRounds = new HashSet<Round>();
        }
    
        public string Name { get; set; }
        public string Country { get; set; }
    
        public virtual Country RelatedCountry { get; set; }
        public virtual ICollection<Round> RelatedRounds { get; set; }
    }
}
